### ISSUE TITLE
Keyframe Easing & Defaults

### ISSUE THREAD

**Issue by Martin-Pitt** [gibbok/keyframes-tool#1]
Per same issue as in https://github.com/gibbok/animatelo/issues/2

Keyframes in CSS Animations by default have: `animation-timing-function: ease`
Keyframes in Web Animations spec by default have: `easing: linear`

So when converting CSS Animations to their equivalent in Web Animations, you need to:

1. Setup a default for all keyframes to `"ease"`
2. Translate `animation-timing-function` property to the `easing` property to match the spec

**Comment by gibbok** [comment]
Issue solved and fix is available at https://github.com/gibbok/keyframes-tool/releases/tag/1.0.3
